services:
  - type: web
    name: interior-design-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run_app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4